//docker-compose file for springboot and postgres
version: '2'
  services:
    postgres:
      image: postgres
      container_name: postgres
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      restart: always
    springboot:
      image: springboot
      container_name: springboot
      ports:
        - "8080:8080"
      depends_on:
        - postgres
      environment:
        SPRING_PROFILES_ACTIVE: prod
      volumes:
        - springboot_data:/usr/src/app/
      restart: always