
server:
  port: 8083
debug: false
logging :
  file:
    name: SpringBootTest.log
    path: /karun
spring:
  application:
    name: SpringBootTest
    version: 1.0.0
  datasource:
     url: jdbc:postgresql://localhost:5432/testdb?useSSL=false
     username: postgres
     password: postgres
  jpa:
     show-sql: true
     properties:
         hibernate:
             dialect: org.hibernate.dialect.PostgreSQLDialect
     hibernate:
         ddl-auto: update
  mail:
    host: 
    port: 587
    username: 
    password: 
    protocol: smtp
    default-encoding: UTF-8
    test-connection: false
    properties:
      mail:
        smtp:
          starttls :
            enable : true
         
management:
  endpoints:
    web:
      exposure:
        include: '*'
           
